variables:
  FORCE_COLOR: '3'

stages:
  - build

build_and_test:
  stage: build
  #  tags:
  #    - macmini
  only:
    refs:
      - develop
      - master
  image: node:14.16.0-buster-slim
  script:
    - node -v
    - npm install npm -g
    - npm install
    - npm run build
    - npm run atat fetch-pairs binance eth
    - npm run atat fetch-pairs ftx perp
    - npm run atat fetch-pairs binanceus usdt
    - npm run atat fetch-pairs bittrex btc
    - npm run atat fetch-pairs binancefutures usdt
    - echo "//registry.npmjs.org/:_authToken=${NPM_PUBLISH_KEY}" >> .npmrc
    - echo "email=${NPM_PUBLISH_EMAIL}" >> .npmrc
    - echo always-auth=true >> .npmrc
    - cat .npmrc
    - npm run release-ci
