variables:
  FORCE_COLOR: '3'

image: node:14.16.0-buster-slim

stages:
  - build
  - test
  - deploy

build:
  stage: build
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
  #  tags:
  #    - macmini
  only:
    refs:
      - develop
      - master
  cache:
    paths:
      - node_modules/
      - dist/
  artifacts:
    expire_in: 1 days
    when: on_success
    paths:
      - node_modules/
      - dist/
  script:
    - node -v
    - npm install npm -g
    - npm ci
    - npm run build

test:
  stage: test
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
  dependencies:
    - build
  cache:
    paths:
      - coverage/
  artifacts:
    paths:
      - coverage/
    when: always
    reports:
      junit:
        - junit.xml
      cobertura: coverage/cobertura-coverage.xml
  script:
    - chmod 755 ./dist/cli.js
    - npm run atat fetch-symbols binance eth
    - npm run atat fetch-symbols binanceus usdt
    - npm run atat fetch-symbols bittrex btc
    - npm run atat fetch-symbols binancefutures usdt
    - npm run atat fetch-symbols bybit
    - npm run test:ci

pages:
  stage: deploy
  dependencies:
    - test
  script:
      - mkdir .public
      - cp -r coverage/* .public
      - mv .public public
  artifacts:
     paths:
      - public
  only:
      - master

deploy_npm:
  stage: deploy
  dependencies:
    - test
  cache:
    paths:
      - node_modules/
  script:
    - echo "//registry.npmjs.org/:_authToken=${NPM_PUBLISH_KEY}" >> .npmrc
    - echo "email=${NPM_PUBLISH_EMAIL}" >> .npmrc
    - echo always-auth=true >> .npmrc
    #- cat .npmrc
    # we only release master from the development machine manually
    #- "[[ ${CI_COMMIT_BRANCH} != 'master' ]] &&
    - "npx release-it prerelease --config .release-it.ci.json --ci --no-git --verbose --preReleaseId='${CI_COMMIT_SHORT_SHA}'"
  only:
    - develop
