variables:
  FORCE_COLOR: '3'

stages:
  - build

build_and_test:
  stage: build
  #  tags:
  #    - macmini
  only:
    refs:
      - develop
      - master
  image: node:14.16.0-buster-slim
  script:
    - node -v
    - npm install npm -g
    - npm install
    - npm run build
    - npx atat fetch-pairs binance eth
    - npx atat fetch-pairs ftx btc
    - npx atat fetch-pairs binanceus usdt
    - npx atat fetch-pairs bittrex btc
