variables:
  FORCE_COLOR: '3'

stages:
  - build

build_and_test:
  stage: build
  #  tags:
  #    - macmini
  only:
    refs:
      - develop
      - master
  image: node:14.16.0-buster-slim
  script:
    - node -v
    - npm install npm -g
    - npm install
    - npm run build
    - npm run fetch:binance eth
    - npm run fetch:ftx btc
    - npm run fetch:binanceus usdt
    - npm run fetch:bittrex btc
